language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

dist: trusty

branches:
  only:
    - master

git:
  depth: 5

php:
  - 7.0
  - 7.1
  - 7.2
  - hhvm
  - nightly
  
matrix:
  fast_finish: true
  include:
    - php: 7.1
      env: PHPCS=PSR2

  allow_failures:
    - php: nightly

before_install:
    - sudo apt-get update
    - sudo apt-get install gnome-terminal

before_script:
  - gnome-terminal -e 'php -S localhost:8000 -t tests/'
  - export PATH="./vendor/bin:$PATH"
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source --dev

script:
  - |
    if [[ "$PHPCS" ]] ; then
      phpcs --standard=phpcs.xml $(find . -name '*.php')
      phpmd src,tests text ./phpmd.xml
    fi
  - phpunit

after_success:
 - bash <(curl -s https://codecov.io/bash)
